openapi: 3.0.0
info:
  version: 0.0.5-beta
  title: storage-management-system
servers:
  - url: 'http://140.124.181.74:30000'
paths:
  /storage:
    get:
      summary: List all storage
      operationId: listStorage
      tags:
        - Storage
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 200
                message: OK
                data:
                - id: 5ca09fac30aed701833897ab
                  chartName: stable/minio
                  releaseName: happy-tree
                  config:
                    accessKey: aclab
                    secretKey: csie1226
                    persistence.size: 2G
                    service.type: NodePort
                    service.nodePort: ""
                    resources.limits.memory: 512Mi
                  endpoint:
                    host: 140.124.181.74
                    port: 32116
                  status: scheduling
                  persistentVolumeClaim:
                    id: pvc-540f7969-53a5-11e9-9c02-14dda9d3e858
                    size: 101380096
                    capacity: 2147483648
                  prometheusUrl:
                    CPU: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-srzf4/api/v1/namespaces/prometheus/services/http:prometheus-grafana:80/proxy/d-solo/pECWlF6ik/pods?orgId=1&var-namespace=default&var-pod=wobbling-turkey-minio-6b956486c-442mg&var-container=All&refresh=5s&panelId=2&theme=light
                    Memory: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-srzf4/api/v1/namespaces/prometheus/services/http:prometheus-grafana:80/proxy/d-solo/pECWlF6ik/pods?orgId=1&var-namespace=default&var-pod=wobbling-turkey-minio-6b956486c-442mg&var-container=All&refresh=5s&panelId=1&theme=light
                    Network: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-srzf4/api/v1/namespaces/prometheus/services/http:prometheus-grafana:80/proxy/d-solo/pECWlF6ik/pods?orgId=1&var-namespace=default&var-pod=wobbling-turkey-minio-6b956486c-442mg&var-container=All&refresh=5s&panelId=3&theme=light
                  resources:
                  - name: v1beta2/Deployment
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/Service
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/Secret
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/Pod(related)
                    resources:
                    - wobbling-turkey-minio-6b956486c-442mg
                  - name: v1/PersistentVolumeClaim
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/ConfigMap
                    resources:
                    - wobbling-turkey-minio
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 500
                message: Internal Server Error
    post:
      summary: Create a storage
      operationId: createStorage
      tags:
        - Storage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Storage'
            example:
              chartName: stable/minio
              config:
                accessKey: aclab
                secretKey: csie1226
                persistence.size: 2G
                service.type: NodePort
                service.nodePort: ""
                resources.limits.memory: 512Mi
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 201
                message: Created
                data:
                  id: 5ca09fac30aed701833897ab
                  chartName: stable/minio
                  releaseName: happy-tree
                  config:
                    accessKey: aclab
                    secretKey: csie1226
                    persistence.size: 2G
                    service.type: NodePort
                    service.nodePort: ""
                    resources.limits.memory: 512Mi
                  endpoint:
                    host: 140.124.181.74
                    port: 32116
                  status: scheduling
                  persistentVolumeClaim:
                    id: pvc-540f7969-53a5-11e9-9c02-14dda9d3e858
                    size: 101380096
                    capacity: 2147483648
                  prometheusUrl:
                    CPU: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-srzf4/api/v1/namespaces/prometheus/services/http:prometheus-grafana:80/proxy/d-solo/pECWlF6ik/pods?orgId=1&var-namespace=default&var-pod=wobbling-turkey-minio-6b956486c-442mg&var-container=All&refresh=5s&panelId=2&theme=light
                    Memory: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-srzf4/api/v1/namespaces/prometheus/services/http:prometheus-grafana:80/proxy/d-solo/pECWlF6ik/pods?orgId=1&var-namespace=default&var-pod=wobbling-turkey-minio-6b956486c-442mg&var-container=All&refresh=5s&panelId=1&theme=light
                    Network: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-srzf4/api/v1/namespaces/prometheus/services/http:prometheus-grafana:80/proxy/d-solo/pECWlF6ik/pods?orgId=1&var-namespace=default&var-pod=wobbling-turkey-minio-6b956486c-442mg&var-container=All&refresh=5s&panelId=3&theme=light
                  resources:
                  - name: v1beta2/Deployment
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/Service
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/Secret
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/Pod(related)
                    resources:
                    - wobbling-turkey-minio-6b956486c-442mg
                  - name: v1/PersistentVolumeClaim
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/ConfigMap
                    resources:
                    - wobbling-turkey-minio
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 500
                message: Internal Server Error
  '/storage/{releaseName}':
    get:
      summary: Info for a specific storage
      operationId: showStorageById
      tags:
        - Storage
      parameters:
        - name: releaseName
          in: path
          required: true
          description: The id of the storage to retrieve
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 200
                message: OK
                data:
                  id: 5ca09fac30aed701833897ab
                  chartName: stable/minio
                  releaseName: happy-tree
                  config:
                    accessKey: aclab
                    secretKey: csie1226
                    persistence.size: 2G
                    service.type: NodePort
                    service.nodePort: ""
                    resources.limits.memory: 512Mi
                  endpoint:
                    host: 140.124.181.74
                    port: 32116
                  status: scheduling
                  persistentVolumeClaim:
                    id: pvc-540f7969-53a5-11e9-9c02-14dda9d3e858
                    size: 101380096
                    capacity: 2147483648
                  prometheusUrl:
                    CPU: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-srzf4/api/v1/namespaces/prometheus/services/http:prometheus-grafana:80/proxy/d-solo/pECWlF6ik/pods?orgId=1&var-namespace=default&var-pod=wobbling-turkey-minio-6b956486c-442mg&var-container=All&refresh=5s&panelId=2&theme=light
                    Memory: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-srzf4/api/v1/namespaces/prometheus/services/http:prometheus-grafana:80/proxy/d-solo/pECWlF6ik/pods?orgId=1&var-namespace=default&var-pod=wobbling-turkey-minio-6b956486c-442mg&var-container=All&refresh=5s&panelId=1&theme=light
                    Network: https://acl.csie.ntut.edu.tw:3000/k8s/clusters/c-srzf4/api/v1/namespaces/prometheus/services/http:prometheus-grafana:80/proxy/d-solo/pECWlF6ik/pods?orgId=1&var-namespace=default&var-pod=wobbling-turkey-minio-6b956486c-442mg&var-container=All&refresh=5s&panelId=3&theme=light
                  resources:
                  - name: v1beta2/Deployment
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/Service
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/Secret
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/Pod(related)
                    resources:
                    - wobbling-turkey-minio-6b956486c-442mg
                  - name: v1/PersistentVolumeClaim
                    resources:
                    - wobbling-turkey-minio
                  - name: v1/ConfigMap
                    resources:
                    - wobbling-turkey-minio
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 500
                message: Internal Server Error
    delete:
      summary: Delete a specific storage
      operationId: deleteStorageById
      tags:
        - Storage
      parameters:
        - name: releaseName
          in: path
          required: true
          description: The id of the storage to retrieve
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 200
                message: OK
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
              example:
                code: 500
                message: Internal Server Error
components:
  schemas:
    Storage:
      required:
        - chartName
        - config
      properties:
        id:
          type: string
        chartName:
          type: string
        releaseName:
          type: string
        config:
          type: object
        endpoint:
          type: string
        status:
          type: string
    Response:
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
        data:
          type: object
        error:
          type: string
